name: simple_ticket
description: "Easy/Cheap crm"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  url_launcher: ^6.3.1
  infinite_scroll_pagination: ^4.1.0
  carousel_slider: ^5.0.0
  html: ^0.15.5
  excel: ^4.0.6
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Specify all assets
  assets:
    - assets/  # This will include all files in the assets folder